CRUD functionality for news, faq and docs
frigvid/mob3000-group11 pull request #13
Opened 2024-11-03 22:23 UTC by 258030

There are instances of double validation, some redundant null checks and it lacks abstraction (the usecases are a must)

The next sprint (from 4.11-19.11) will inlcude a final and polished version, where we hopefully also can abstract the general CRUD funcitonalities across the application (if we have time)

2024-11-03 23:39 UTC, frigvid commented on .idea/deploymentTargetSelector.xml
Machine-specific configurations should not be committed. This will fail on every other computer, and should be removed from the commit. Remember to use `.gitignore`.

2024-11-04 01:42 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/data/model/content/DocsDto.kt
> +    val docId: String? = null,
Documentation will always have an ID. This change makes the tabulated data more difficult to work with and needs to be reverted.

2024-11-04 01:43 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/data/model/content/FaqDto.kt
> +    val faqId: String? = null,
FAQ items will always have an ID. This change makes the tabulated data more difficult to work with and needs to be reverted.

2024-11-04 01:43 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/data/model/content/NewsDto.kt
> +    val newsId: String? = null,
News items will always have an ID. This change makes the tabulated data more difficult to work with and needs to be reverted.

2024-11-04 01:43 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/data/repository/content/DocsRepository.kt
KDoc strings need to be extended and properly reflect the code they're documenting.

2024-11-04 01:43 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/data/repository/content/FAQRepository.kt
KDoc strings need to be extended and properly reflect the code they're documenting.

2024-11-04 01:44 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/data/repository/content/NewsRepository.kt
KDoc strings need to be extended and properly reflect the code they're documenting.

2024-11-04 01:45 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/data/repository/content/DocsRepository.kt
> +            docId = null,
Documentation items always have an ID, when using a tabulated data structure representing the database table, you must ensure that it reflects it. This cannot be null.

2024-11-04 01:46 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/data/repository/content/FAQRepository.kt
> +            faqId = null,
FAQ items always have an ID, when using a tabulated data structure representing the database table, you must ensure that it reflects it. This cannot be null.

2024-11-04 01:46 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/data/repository/content/NewsRepository.kt
> +            newsId = null,
News items always have an ID, when using a tabulated data structure representing the database table, you must ensure that it reflects it. This cannot be null.

2024-11-04 01:47 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/data/source/remote/content/DocsDataSource.kt
KDoc strings need to be extended and properly reflect the code they're documenting.

2024-11-04 01:48 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/data/source/remote/content/FAQDataSource.kt
KDoc strings need to be extended and properly reflect the code they're documenting.

2024-11-04 01:49 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/data/source/remote/content/NewsDataSource.kt
KDoc strings need to be extended and properly reflect the code they're documenting.

2024-11-04 02:03 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/model/content/DocumentationStruct.kt
> +data class DocsUpdateData(
Working with data structures that don't represent the database tables, shouldn't make it necessary to have different structs for "updated" data. An object should always represent its latest state, and so, the updated data should just be written to the `DocsData` struct instead.

2024-11-04 02:03 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/model/content/FaqStruct.kt
> +data class FaqUpdateData(
Working with data structures that don't represent the database tables, shouldn't make it necessary to have different structs for "updated" data. An object should always represent its latest state, and so, the updated data should just be written to the `FAQData` struct instead.

2024-11-04 02:04 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/model/content/NewsStruct.kt
> +data class NewsUpdateData(
Working with data structures that don't represent the database tables, shouldn't make it necessary to have different structs for "updated" data. An object should always represent its latest state, and so, the updated data should just be written to the `NewsData` struct instead.

2024-11-04 02:10 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/viewmodel/CBViewModel.kt
I've fixed it now, but remember to not nuke comments. If you do, replace them with equivalents in quality, or undo the removal if the code it represents hasn't changed enough to warrant a new comment.

2024-11-04 02:15 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/ui/components/info/ContentEditor.kt
> +                label = { Text(stringResource(R.string.news_update_title)) },
Incorrect typing. If it's going to be generic, it should either use generic text, or check the type and choose relative to that.

2024-11-04 02:16 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/ui/components/info/ContentEditor.kt
> +                label = { Text(stringResource(R.string.news_create_label_summary)) },
Incorrect typing. If it's going to be generic, it should either use generic text, or check the type and choose relative to that.

2024-11-04 02:16 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/ui/components/info/ContentEditor.kt
> +                label = { Text(stringResource(R.string.news_create_label_content)) },
Incorrect typing. If it's going to be generic, it should either use generic text, or check the type and choose relative to that.

2024-11-04 02:16 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/ui/components/info/ContentEditor.kt
> +                Text(stringResource(R.string.news_create_check_publish))
Incorrect typing. If it's going to be generic, it should either use generic text, or check the type and choose relative to that.

2024-11-04 02:16 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/ui/components/info/ContentEditor.kt
> +                Text(stringResource(R.string.news_create_save_changes))
Incorrect typing. If it's going to be generic, it should either use generic text, or check the type and choose relative to that.

2024-11-04 02:17 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/ui/components/info/ContentEditor.kt
> + * @contributor 258030
Note, author should not be changed when simply extracting existing code with minimal changes.

2024-11-04 02:17 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/ui/components/info/ContentItem.kt
> +@Composable
KDoc string needs to be expanded.

2024-11-04 02:25 UTC, frigvid requested changes
This is not ready to merge to master. There are a number of issues, currently, though I've fixed some of it. And a lot of spacing issues. There are a good number of KDoc strings that need to be updated, etc. I'd do it myself, but I really want to sleep right now. I'm kind of too tired to give you a point-by-point on what should be fixed, but I've commented a bit here and there. News, Docs, and FAQ items are lacking a highlighted outline representing their publishing state, for one.

As an aside, remember that navigation should not handle logic. When you pass ViewModel values or functions to a screen, you do not do so by passing the entire ViewModel. You inject the specific function or value that you need at that moment. Same with dual inputs, parameters in navigation should be 1-to-1, not 1-to-many. Makes it harder to test. I've also parameterized some things, also to make them easier to test.

***e:*** News, documentation and FAQs are all relatively static in the sense that they aren't often changed. Nor are they account dependent. These would be well served by a local database to store the different items, and then simply update that via a worker or some such to keep it updated.

2024-11-04 23:03 UTC, 258030 commented on app/src/main/java/no/usn/mob3000/data/repository/content/NewsRepository.kt
> +            newsId = null,
Have reverted it as asked, onboard with having Id = UUID.randomUUID().toString()?

2024-11-04 23:07 UTC, 258030 commented on app/src/main/java/no/usn/mob3000/data/model/content/DocsDto.kt
Reverted

2024-11-04 23:16 UTC, Kveggjeter reviewed
Mostly KDoc issues, should be on par with the rest of the application.

Took care of uncessecary dependency across layers and removed null refferances. The most important part is that the functionality is there. Will start to work on the last items on my backlock after it's ready for merging. A lot of my new feats and abstraction are dependant on the authentication functionality.

2024-11-04 23:16 UTC, Kveggjeter commented on app/src/main/java/no/usn/mob3000/data/model/content/FaqDto.kt
Reverted

2024-11-04 23:16 UTC, Kveggjeter commented on app/src/main/java/no/usn/mob3000/data/model/content/NewsDto.kt
Reverted

2024-11-04 23:16 UTC, 258030 commented on app/src/main/java/no/usn/mob3000/data/repository/content/DocsRepository.kt
Did some commenting, let me know

2024-11-04 23:16 UTC, 258030 commented on app/src/main/java/no/usn/mob3000/data/repository/content/FAQRepository.kt
Did some commenting, let me know

2024-11-04 23:16 UTC, 258030 commented on app/src/main/java/no/usn/mob3000/data/repository/content/NewsRepository.kt
Did some commenting, let me know

2024-11-04 23:16 UTC, 258030 commented on app/src/main/java/no/usn/mob3000/data/source/remote/content/DocsDataSource.kt
Did some commenting, let me know

2024-11-04 23:16 UTC, 258030 commented on app/src/main/java/no/usn/mob3000/data/source/remote/content/FAQDataSource.kt
Did some commenting, let me know

2024-11-04 23:16 UTC, 258030 commented on app/src/main/java/no/usn/mob3000/data/source/remote/content/NewsDataSource.kt
Did some commenting, let me know

2024-11-04 23:16 UTC, 258030 commented on app/src/main/java/no/usn/mob3000/domain/model/content/DocumentationStruct.kt
Removed as requested

2024-11-04 23:16 UTC, 258030 commented on app/src/main/java/no/usn/mob3000/data/source/remote/content/NewsDataSource.kt
Also made the the methods more similar, no reason for pushing it as JSON for inserting and updating*

2024-11-04 23:16 UTC, 258030 commented on app/src/main/java/no/usn/mob3000/ui/components/info/ContentItem.kt
> +@Composable
Did some commenting, let me know

2024-11-06 23:13 UTC, closed without merging