Hussein endringer
frigvid/mob3000-group11 pull request #15
Opened 2024-11-05 23:16 UTC by Husseinabdulameer11

2024-11-05 23:18 UTC, Anarox1111 commented
First

2024-11-06 10:52 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/data/repository/social/FriendsRepository.kt
> +/**
Remember spacing.

2024-11-06 10:52 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/data/repository/social/FriendsRepository.kt
> +* @author Hussein Abdul-Ameer
Remember to use GitHub user names, this is defined in our internal docs.

2024-11-06 10:53 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/data/repository/social/FriendsRepository.kt
> +* created on 05.11.2024
Remember to conform to repository date standards. Everywhere else is using ISO8601.

2024-11-06 10:53 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/data/repository/social/FriendsRepository.kt
> +):IFriendsRepository{
Remember spacing.

2024-11-06 10:55 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/data/repository/social/FriendsRepository.kt
There's quite a few spacing issues in this file, that needs to be fixed. Additionally, code needs to conform to Kotlin's and Android Developers' code style guidelines.

2024-11-06 10:57 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/data/source/remote/social/FriendsDataSource.kt
> +            .from("friends")
Remember to look through the existing database code and see if there are RPC functions that you can use. In this case, there are functions to get friends already and may be useful here compared to simply selecting from the friends table.

2024-11-06 10:58 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/data/source/remote/social/FriendsDataSource.kt
Remember KDocs.

2024-11-06 10:58 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/model/social/FriendData.kt
> +
Remember spacing.

2024-11-06 10:58 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/model/social/FriendData.kt
> +**/
Incorrect docstring end.

2024-11-06 10:59 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/model/social/FriendData.kt
> +* created on 05.11.2024
You are not using a docstring parameter for creation date. Additionally, creation date must conform with ISO8601.

2024-11-06 10:59 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/model/social/FriendData.kt
> +/**
Remember spacing.

2024-11-06 10:59 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/model/social/FriendData.kt
> +* @author Hussein Abdul-Ameer
Remember to use GitHub usernames, nor real names.

2024-11-06 11:02 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/repository/IFriendsRepository.kt
> +
Remember spacing.

2024-11-06 11:02 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/repository/IFriendsRepository.kt
> + * created on: 02.11.2024
As before, use GitHub usernames and ISO8601 conformed dates. Additionally remember to use KDoc string parameter. Remember also that file docstrings should be the first thing in a file, and that the only reason for it to exist is if the file in question needs special considerations. E.g. to inform other developers of something. If not, then use docstrings as usual.

2024-11-06 11:02 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/repository/IFriendsRepository.kt
> +// In IFriendsRepository
Incorrect file-level docstrings. Should be removed.

2024-11-06 11:02 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/repository/IFriendsRepository.kt
> +interface IFriendsRepository {
Remember KDocs.

2024-11-06 11:02 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/repository/IFriendsRepository.kt
> +suspend fun FetchFriends(): Result<List<FriendData>>
Remember spacing.

2024-11-06 11:02 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/usecase/social/FetchFriendsUseCase.kt
> +class FetchFriendsUseCase (
Remember KDocs.

2024-11-06 11:04 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/viewmodel/ProfileViewModel.kt
> + * created on : 01.11.2024
Remember to use GitHub usernames and ISO8601 conformed dates. Additionally, this is an incorrectly placed top-level docstring, and this file does not need one that has special considerations. This should be removed. Instead, document classes, objects, functions and such as normal.

2024-11-06 11:04 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/viewmodel/ProfileViewModel.kt
> +class ProfileViewModel(
Remember KDocs.

2024-11-06 11:04 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/viewmodel/ProfileViewModel.kt
> +
Remember spacing.

2024-11-06 11:05 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/viewmodel/ProfileViewModel.kt
> +    }
Inits in ViewModels are very often not necessary. Consider if the structure actually needs this, or if it was just the simpler option, where there is a better option elsewhere. E.g. for making Unit testing easier, etc.

2024-11-06 11:05 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/viewmodel/ProfileViewModel.kt
> +    private fun loadFriends() {
Remember KDocs.

2024-11-06 11:06 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/viewmodel/socials/ProfileViewModel.kt
> +/**
Remember spacing.

2024-11-06 11:06 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/viewmodel/socials/ProfileViewModel.kt
> +class ProfileViewModel (
Remember spacing.

2024-11-06 11:07 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/viewmodel/socials/ProfileViewModel.kt
> +* created on 05.11.2024
Remember to use GitHub usernames and ISO8601 conformed dates. Additionally, this has been a problem in every one: Remember to actually use the KDoc. They're there to describe the class, function, object, etc. If they are empty, they serve little to no purpose.

2024-11-06 11:08 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/viewmodel/socials/ProfileViewModel.kt
> +   val selectedFriend: State<FriendData?> = _selectedFriend
Remember spacing.

2024-11-06 11:08 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/viewmodel/socials/ProfileViewModel.kt
> +):ViewModel(){
Remember spacing.

2024-11-06 11:08 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/domain/viewmodel/socials/ProfileViewModel.kt
> +private val _friends = MutableStateFlow<Result<List<FriendData>>>(Result.success(emptyList()))
Remember spacing.

2024-11-06 11:09 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/ui/screens/user/ProfileScreen.kt
> +}
Remember spacing.

2024-11-06 11:09 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/ui/screens/user/ProfileScreen.kt
>  fun ProfileScreen(
Remember KDocs.

2024-11-06 11:13 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/ui/screens/user/ProfileScreen.kt
> +fun friendComponent(friendResult: Result<List<FriendData>>) {
This naming will be confusing. A friend component suggests that this is a component of _one_ friend, not a component for fitting all friends into a column per row per user that is friends with the authenticated user. Additionally, it should be extracted to the components package in a relevant sub-package.

2024-11-06 11:17 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/ui/screens/user/ProfileScreen.kt
If you are going to use AI, then at the very least make sure that the code works and remove the very obvious signs of AI usage _before_ you commit. :/ Preferably, don't use AI at all. And especially don't just copy-paste, which I suspect has happened, considering the nuked KDoc.

Remember that since you are clearly using AI, you'll need APA7 documentation for every single thread used with the AI, and that needs to be documented in the final report when documenting how the logic implementation works. If it's obvious in a commit, it's also obvious to the governing body judging that final report and that'll affect your final grading.

2024-11-06 11:17 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/ui/screens/user/ProfileScreen.kt
> +                        .clickable { /* Add click handling here if needed */ }
Unnecessary comment.

2024-11-06 11:17 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/ui/screens/user/ProfileScreen.kt
> +                            text = it,  // Assuming `FriendSingleDto` has a `displayName` property
Unnecessary, very AI comment.

2024-11-06 11:18 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/ui/screens/user/ProfileScreen.kt
> +            // Handle the error case if needed, such as showing an error message
Unnecessary comment.

2024-11-06 11:18 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/ui/screens/user/ProfileScreen.kt
> +                    text = "Failed to load friends",
Remember to extract to string resource.

2024-11-06 11:19 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/ui/screens/user/ProfileScreen.kt
>  fun ProfileScreen(
Wait. Smooth brained here, ignore this one.

2024-11-06 11:20 UTC, frigvid commented on app/src/main/java/no/usn/mob3000/ui/screens/user/ProfileScreen.kt
> +fun FriendsSection(friendResult: Result<List<FriendData>>) {
Remember spacing and KDocs.

2024-11-06 11:22 UTC, frigvid requested changes
There are a good few spacing issues, missing KDocs, malformed ISO8601 dates, incorrect author names, etc. I've commented a fair bit, but in this case I'm somewhat strapped for time, so I've only done it via GitHub's UI. Regardless, refer to those comments.

2024-11-19 15:30 UTC, frigvid commented
See: https://github.com/frigvid/mob3000-group11/pull/25/files

2024-11-19 15:30 UTC, closed without merging